name: Prepare UV environment
description: |
  Install, configure, and Sync a UV environment.

runs:
  using: "composite"

  steps:
    - name: Install UV
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1

    - name: Sync UV
      shell: bash
      run: |
        uv sync --all-extras
