---
# Clock Frequency (in Hz)
clockFreq: 1000

# Video output
video:
  width: 640
  height: 480
  scale: 2

# Data-bus and peripherals
dataBus:
  - start: 0x0000
    end: 0x3FFF
    peripheral:
      type: ram

  - start: 0xFF00
    end: 0xFFFF
    peripheral:
      type: rom
      load: systems/default.rom.bin

  - start: 0x8000
    end: 0x8000
    peripheral:
      type: terminal

  - start: 0x8010
    end: 0x8010
    peripheral:
      type: keyboard
