---
# Clock Frequency (in Hz)
clockFreq: 1000

# Data-bus and peripherals
dataBus:
  - start: 0x0000
    end: 0x3FFF
    peripheral:
      type: ram

  - start: 0xFF00
    end: 0xFFFF
    peripheral:
      type: rom
      load: default.rom.bin

  - start: 0x8000
    end: 0x8000
    peripheral:
      type: terminal
