name: Unit Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        runner-os: [ubuntu-latest]
        zig-version: [master]

    runs-on: ${{ matrix.runner-os }}
    name: "zig v${{ matrix.zig-version }} on ${{ matrix.runner-os }}"
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Code style enforcement
        run: zig fmt --check src

      - name: Run unit-tests
        run: zig build test
